#!/usr/bin/env bash
#
# Check for disk busy on SmartOS
#
# Author: Dave Eddy <dave@voxer.com>
# Date: 11/16/12
# License: MIT

function busy() {
	iostat -xr 1 2 |\
	awk -F, '
	BEGIN {
		max = -1;
	}
	/^sd[0-9]/ {
		d = $1;
		sub(/^sd/,"",d);
		if (d > max) {
			max = d;
			next;
		}
		if ($2||$3||$4||$5||$6||$7||$8||$9) {
			i++;
			busy+=$10;
		}
	}
	END {
		if (i) {
			printf("%d\n", (busy / i) + .5);
		} else {
			print "0"
		}
	}'
}

warning=90
critical=95
perfdata=true
while getopts 'nw:c:' option; do
	case "$option" in
		n) perfdata=false;;
		w) warning=$OPTARG;;
		c) critical=$OPTARG;;
	esac
done
shift $((OPTIND - 1))

busy=$(busy)

# alert
if [[ -z $busy ]]; then
	echo 'unknown: error retrieving data'
	exit 3
elif (( busy >= critical )); then
	echo -n 'critical: '
	ret=2
elif (( busy >= warning )); then
	echo -n 'warning: '
	ret=1
else
	echo -n 'ok: '
	ret=0
fi

echo -n "disk $busy% busy (warning=$warning%, critical=$critical%)"
$perfdata && echo "|disk_busy=$busy" || echo
exit "$ret"
