#!/usr/bin/env bash
#
# Check the zone memory cap, and alert if we are over
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: 8/30/13
# License: MIT

nover=$(kstat -p 'memory_cap:::nover' | awk '{print $2}')

if [[ -z "$nover" ]]; then
	echo 'unknown: nover could not be determined'
	exit 3
fi

if (( nover == 0 )); then
	ret=0
	echo -n 'ok: '
else
	ret=2
	echo -n 'critical: '
fi

echo -n "nover is $nover"

if [[ $1 == '-n' ]]; then
	echo
else
	echo "|nover=$nover"
fi

exit "$ret"
