#!/usr/bin/env bash
#
# Check the zone memory cap, and alert if we are over
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: 8/30/13
# License: MIT

nover=$(kstat -p 'memory_cap:::nover' | awk '{print $2}')

if [[ -z "$nover" ]]; then
	echo 'unknown: nover could not be determined'
	exit 3
elif (( nover == 0 )); then
	echo 'ok: nover is 0'
	exit 0
else
	echo "critical: nover is $nover"
	exit 2
fi
